url: https://kimos-production.github.io
baseurl: /

# Site settings
title: KIMOS Production
email: kimos.production@gmail.com
description: ""KIMOS Production is a specialized agency dedicated to cultivating and managing AI influencers. As an innovative leader in the digital influencer space, KIMOS Production leverages advanced AI technologies to create and promote virtual personalities tailored to various markets and audiences. For more details, please visit our website at https://kimos-production.github.io/. You can also contact us via email at kimos.production@gmail.com. Explore the future of digital influence with KIMOS Production!""

# Team names, titles and social links
people:
- name: Kimos
  pic: 1
  position: Executive Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/kimos-production

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty